packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [ gcc@11.2.0, cce@15.0.0, aocc@3.2.0 ]
    providers:
      mpi: [ cray-mpich ]
      blas: [ cray-libsci ]
      lapack: [ cray-libsci ]
      scalapack: [ cray-libsci ]
      fftw-api: [ cray-fftw ]
      pkgconfig: [ pkg-config ]
    permissions:
      read: world
      write: user

# don't build virtuals with an external provider
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
  fftw-api:
    buildable: false
  pkgconfig:
    buildable: false
  cce:
    buildable: false
  gcc:
    buildable: false
  aocc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false

# for end users apps, prefer cmake variant build_type=Release
  caliper:
    variants: 'build_type=Release'
  gromacs:
    variants: 'build_type=Release'
  lammps:
    variants: 'build_type=Release'
  nektar:
    variants: 'build_type=Release'
  visit:
    variants: 'build_type=Release'

# packages found automatically by spack external find
#
  pkg-config:
    externals: []
  diffutils:
    externals: []
  binutils:
    externals:
    - spec: binutils@2.38
      prefix: /opt/cray/pe/cce/15.0.0/binutils/x86_64/x86_64-pc-linux-gnu
    - spec: binutils@2.39.0
      prefix: /usr
    buildable: false
  m4:
    externals: []
  cmake:
    externals:
    - spec: cmake@3.20.4
      prefix: /usr
  subversion:
    externals:
    - spec: subversion@1.14.1
      prefix: /usr
    buildable: false
  bison:
    externals: []
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
    buildable: false
  findutils:
    externals: []
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
    buildable: false
  gmake:
    externals: []
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
    buildable: false
  texinfo:
    externals: []
  git:
    externals:
    - spec: git@2.35.3~tcltk
      prefix: /usr
    buildable: false
  flex:
    externals: []
# getting rid of letter in version, as clingo/spack has buggy behaviour
# fooling spack is risky; however, openssh website mentions 
# these 2 versions are equivalent; also seem equivalent within spack
  openssh:
    externals:
#    - spec: openssh@8.4p1
    - spec: openssh@8.4
      prefix: /usr
    buildable: false
  gawk:
    externals: []
  curl:
    externals:
    - spec: curl@7.79.1+gssapi+ldap+nghttp2
      prefix: /usr
    buildable: false
  openssl:
    externals:
# getting rid of letter in version, as clingo/spack has buggy behaviour
# fooling spack is risky; however, as of spack v0.17.0, 
# these 2 versions are equivalent in recipes for depends/conflicts
#    - spec: openssl@1.1.1l
    - spec: openssl@1.1
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
    buildable: false

# system packages (manually added)
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
    buildable: false
  hwloc:
    externals:
    - spec: hwloc@2.5.0
      prefix: /usr
    buildable: false
  libxml2:
    externals:
    - spec: libxml2@2.9.14
      prefix: /usr
    buildable: false
  libpciaccess:
    externals:
    - spec: libpciaccess@0.11.1
      prefix: /usr
    buildable: false
  numactl:
    externals:
    - spec: numactl@2.0.14
      prefix: /usr
    buildable: false
  libfuse:
    externals:
    - spec: libfuse@2.9.7
      prefix: /usr
    buildable: false
  slurm:
    externals:
    - spec: slurm@22-05-8
      prefix: /usr
    buildable: false
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr
    buildable: false
  cryptsetup:
    externals:
    - spec: cryptsetup@2.3.7
      prefix: /usr
    buildable: false
  libseccomp:
    externals:
    - spec: libseccomp@2.5.3
      prefix: /usr
    buildable: false
  libgpg-error:
    externals:
    - spec: libgpg-error@1.29
      prefix: /usr
    buildable: false
  popt:
    externals:
    - spec: popt@1.16
      prefix: /usr
    buildable: false
  lvm2:
    externals:
    - spec: lvm2@2.03
      prefix: /usr
    buildable: false
  blkid:
    externals:
    - spec: blkid@2.36.2
      prefix: /usr
    buildable: false
  util-linux:
    externals:
    - spec: util-linux@2.36.2
      prefix: /usr
    buildable: false
  util-linux-uuid:
    externals:
    - spec: util-linux-uuid@2.36.2
      prefix: /usr
    buildable: false
  time:
    externals:
    - spec: time@1.9
      prefix: /usr
    buildable: false
# cray packages (manually added)
# adding prefixes as in NERSC Perlmutter configs
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.23%gcc
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/gnu/9.1
    - spec: cray-mpich@8.1.23%cce
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0
    - spec: cray-mpich@8.1.23%aocc
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/aocc/3.0
    buildable: false
  cray-libsci:
    externals:
    - spec: cray-libsci@22.12.1.1%gcc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/gnu/9.1/x86_64
    - spec: cray-libsci@21.08.1.2%cce
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/cray/9.0/x86_64
    - spec: cray-libsci@22.08.1.1%aocc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/aocc/2.0/x86_64
    buildable: false
  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.10.3 target=zen2
      modules:
      - craype-x86-rome
      - cray-fftw/3.3.10.3
      prefix: /opt/cray/pe/fftw/3.3.10.3/x86_rome
    buildable: false
  # more cray
  xpmem:
    externals:
    - spec: xpmem@2.4.4
      modules:
      - xpmem/xpmem/2.5.2-2.4_3.30__gd0f7936.shasta
      prefix: /opt/cray/xpmem/xpmem/2.5.2-2.4_3.30__gd0f7936.shasta
    buildable: false
  libfabric:
    externals:
    - spec: libfabric@1.12.1.2.2.0.0
      modules:
      - libfabric/1.12.1.2.2.0.0
      prefix: /opt/cray/libfabric/1.11.0.4.128
    buildable: false
  #ucx:
  #  externals:
  #  - spec: ucx@2.7.0-1
  #    modules:
  #    - cray-ucx/2.7.0-1
  #    prefix: /opt/cray/pe/cray-ucx/2.7.0-1/ucx
  #  buildable: false
  papi:
    externals:
    - spec: papi@6.0.0.17
      modules:
      - papi/6.0.0.17
      prefix: /opt/cray/pe/papi/6.0.0.17
    buildable: false

# python additions, based on loading cray-python and running pip list 
# we have tried to use them as externals, but Spack does not use them correctly:
# 1. if specified with ^python@3.9.7, concretisation always fail
# 2. if specified without ^python@3.9.7, would be used also with the wrong python versions
# therefore, taken out

