packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [ gcc@11.2.0, cce@15.0.0, aocc@3.2.0 ]
    providers:
      mpi: [ cray-mpich ]
      blas: [ cray-libsci ]
      lapack: [ cray-libsci ]
      scalapack: [ cray-libsci ]
      fftw-api: [ cray-fftw ]
      pkgconfig: [ pkg-config ]
    permissions:
      read: world
      write: user

# don't build virtuals with an external provider
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
  fftw-api:
    buildable: false
  pkgconfig:
    buildable: false
  cce:
    buildable: false
  gcc:
    buildable: false
  aocc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false

  # GENERAL NOTES:
  # 1. for each package, only one entry must exist in this yaml
  # otherwise only the last one is considered, and the previous ones are ingored
  # 2. when externals are specified, the preferred version is respected only if it is one of the externals

  # preferred versions and variants, dependencies
  # required by env_devel/hpctoolkit, but good to have for everything
  libunwind:
    variants: '+pic'
  mbedtls:
    variants: '+pic'
  zlib:
    version : [1.2.13]
  # preferred versions and variants, utils/python
  # Note: setting autoconf/automake/cmake as non buildable
  cmake:
    version: [3.21.3]
  ffmpeg:
    version: [4.4]
    variants: '+avresample'
  gnuplot:
    version: [5.4.2]
    variants: '+X'
  python:
    version: [3.9.15]
    variants: '+optimizations +zlib'
  gdbm:
    version: [1.19]
  gettext:
    version: [0.21.1]
  py-cython:
    version: [0.29.24]
  py-dask:
    version: [2021.6.2]
  py-h5py:
    version: [3.4.0]
  py-ipython:
    version: [7.28.0]
  py-matplotlib:
    version: [3.4.3]
    variants: '+movies'
  py-mpi4py:
    version: [3.1.2]
  py-numba:
    version: [0.54.0]
  py-numpy:
    version: [1.20.3]
  py-pandas:
    version: [1.3.4]
  py-pip:
    version: [22.2.2]
  py-plotly:
    version: [5.2.2]
  py-scikit-learn:
    version: [1.0.1]
  py-scipy:
    version: [1.7.1]
  py-setuptools:
    version: [57.4.0]
  # preferred versions and variants, compilers
  go:
    version: [1.16.12]
  julia:
     version: [1.6.1]
  openjdk:
    version: [17.0.0_35]
  r:
    version: [4.1.0]
  perl:
    version: [5.34.0]
  ruby:
    version: [3.0.1]
  rust:
    version: [1.52.1]
  # preferred versions and variants, num_libs
  amdblis:
    version: [3.0]
    variants: 'threads=openmp'
  amdlibflame:
    version: [3.0]
    variants: 'threads=openmp'
  amdscalapack:
    version: [3.0]
    variants: 'build_type=Release'
  aocl-sparse:
    version: [3.0]
    variants: 'build_type=Release'
  amdfftw:
    version: [3.0]
    variants: 'precision=float,double,long_double'
  amdlibm:
    version: [3.0]
  blaspp:
    version: [2021.04.01]
    variants: '~cuda build_type=Release'
  boost:
    version: [1.80.0]
    variants: '+mpi +numpy +python'
  eigen:
    version: [3.4.0]
    variants: 'build_type=Release'
  fftw:
    version: [3.3.9,2.1.5]
    variants: '+openmp precision=float,double,long_double'
  gsl:
    version: [2.6]
  hpx:
    version: [1.6.0]
    variants: '+async_mpi malloc=jemalloc max_cpu_count=128 networking=mpi cxxstd=14 build_type=Release'
  kokkos:
    version: [3.4.01]
    variants: '+hwloc +memkind +numactl +openmp +tuning cxxstd=14 build_type=Release'
  netlib-lapack:
    version: [3.9.1]
    variants: 'build_type=Release'
  openblas:
    version: [0.3.21]
    variants: 'threads=openmp'
  opencv:
     version: [4.5.2]
     variants: 'build_type=Release'
  plasma:
    version: [20.9.20]
    variants: 'build_type=Release'
  petsc:
    version: [3.15.5]
    variants: '+fftw'
  plumed:
    version: [2.7.2]
  netlib-scalapack:
    version: [2.1.0]
  slate:
    version: [2021.05.02]
    variants: '~cuda build_type=Release'
  trilinos:
    version: [13.0.1]
    variants: '+adios2 +openmp +python build_type=Release'
# preferred versions and variants, io_libs
  hdf5:
    version: [1.12.1]
    variants: 'api=v112 +hl +fortran +szip build_type=Release'
  hdf:
    variants: '+external-xdr'
  adios2:
    version: [2.7.1]
    variants: '+python +hdf5 build_type=Release'
  netcdf-c:
    version: [4.8.1]
    variants: '+hdf4 +parallel-netcdf'
  netcdf-cxx:
    version: [4.2]
  netcdf-cxx4:
    version: [4.3.1]
  netcdf-fortran:
    version: [4.5.3]
  parallel-netcdf:
    version: [1.12.2]
  py-h5netcdf:
    version: [0.10.0]
  py-netcdf4:
    version: [1.5.3]
# for end users apps, prefer cmake variant build_type=Release
  caliper:
    variants: 'build_type=Release'
  gromacs:
    variants: 'build_type=Release'
  lammps:
    variants: 'build_type=Release'
  nektar:
    variants: 'build_type=Release'
  visit:
    variants: 'build_type=Release'

  #for astro packages prefer release
  casacore:
    variants: 'build_type=Release'
  everybeam:
    variants: 'build_type=Release'
  wsclean:
    variants: 'build_type=Release'
  idg:
    variants: 'build_type=Release'
  cghcentre:
    variants: 'build_type=Release'

# packages found automatically by spack external find
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
    buildable: false
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
    buildable: false
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: false
  elfutils:
    externals:
    - spec: elfutils@0.168
      prefix: /usr
    buildable: false
  file:
    externals:
    - spec: file@5.32
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
    buildable: false
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
    buildable: false
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
    buildable: false
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
    buildable: false
  git:
    externals:
    - spec: git@2.34.1~tcltk
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
    buildable: false
  lustre:
    externals:
    - spec: lustre@2.15.0.2_rc2_cray_113_g62287d0
      prefix: /usr
    buildable: false
  libelf:
    externals:
    - spec: libelf@0.168
      prefix: /usr
    buildable: false
  libffi:
    externals:
    - spec: libffi@3.2.1
      prefix: /usr
    buildable: false
  libxpm:
    externals:
    - spec: libxpm@3.5.12
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  maven:
    externals:
    - spec: maven@3.6.3
      prefix: /usr/local/maven
    buildable: false
  ninja:
    externals:
    - spec: ninja@1.10.0
      prefix: /usr
    buildable: false
  openssh:
    externals:
# getting rid of letter in version, as clingo/spack has buggy behaviour
# fooling spack is risky; however, openssh website mentions 
# these 2 versions are equivalent; also seem equivalent within spack
#    - spec: openssh@8.4p1
    - spec: openssh@8.4
      prefix: /usr
    buildable: false
  openssl:
    externals:
# getting rid of letter in version, as clingo/spack has buggy behaviour
# fooling spack is risky; however, as of spack v0.17.0, 
# these 2 versions are equivalent in recipes for depends/conflicts
#    - spec: openssl@1.1.1d
    - spec: openssl@1.1
      prefix: /usr
    buildable: false
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false
  readline:
    externals:
    - spec: readline@7.0
      prefix: /usr
    buildable: false
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
    buildable: false
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
    buildable: false
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
    buildable: false
  xz:
    externals:
    - spec: xz@5.2.3+pic
      prefix: /usr
    buildable: false

# system packages (manually added)
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false
  autogen:
    externals:
    - spec: autogen@5.18.12
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
    buildable: false
  binutils:
    externals:
    - spec: binutils@2.37
      prefix: /usr
    buildable: false
  hwloc:
    externals:
    - spec: hwloc@2.5.0
      prefix: /usr
    buildable: false
  libxml2:
    externals:
    - spec: libxml2@2.9.7
      prefix: /usr
    buildable: false
  libpciaccess:
    externals:
    - spec: libpciaccess@0.14
      prefix: /usr
    buildable: false
  numactl:
    externals:
    - spec: numactl@2.0.14
      prefix: /usr
    buildable: false
  sqlite:
    externals:
    - spec: sqlite@3.36.0
      prefix: /usr
    buildable: false
  curl:
    externals:
    - spec: curl@7.66.0
      prefix: /usr
    buildable: false
  libfuse:
    externals:
    - spec: libfuse@2.9.7
      prefix: /usr
    buildable: false
  lz4:
    externals:
    - spec: lz4@1.9.2
      prefix: /usr
    buildable: false
  slurm:
    externals:
    - spec: slurm@20-11-5-1
      prefix: /usr
    buildable: false
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr
    buildable: false
  zstd:
    externals:
    - spec: zstd@1.4.4
      prefix: /usr
    buildable: false
  cryptsetup:
    externals:
    - spec: cryptsetup@2.3.7
      prefix: /usr
    buildable: false
  libseccomp:
    externals:
    - spec: libseccomp@2.5.3
      prefix: /usr
    buildable: false
  libgpg-error:
    externals:
    - spec: libgpg-error@1.29
      prefix: /usr
    buildable: false
  popt:
    externals:
    - spec: popt@1.16
      prefix: /usr
    buildable: false
  icu4c:
    externals:
    - spec: icu4c@65.1
      prefix: /usr
    buildable: false 
  lvm2:
    externals:
    - spec: lvm2@2.03
      prefix: /usr
    buildable: false
  blkid:
    externals:
    - spec: blkid@2.36.2
      prefix: /usr
    buildable: false
  squashfs:
    externals:
    - spec: squashfs@4.4
      prefix: /usr
    buildable: false
  shadow:
    externals:
    - spec: shadow@4.8.1
      prefix: /usr
    buildable: false
  util-linux:
    externals:
    - spec: util-linux@2.36.2
      prefix: /usr
    buildable: false
  util-linux-uuid:
    externals:
    - spec: util-linux-uuid@2.36.2
      prefix: /usr
    buildable: false
  time:
    externals:
    - spec: time@1.9
      prefix: /usr
    buildable: false
  subversion:
    externals:
    - spec: subversion@1.10.6
      prefix: /usr
    buildable: false
  swig:
    externals:
    - spec: swig@3.0.12
      prefix: /usr
    buildable: false
# cray packages (manually added)
# adding prefixes as in NERSC Perlmutter configs
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.23%gcc
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/gnu/9.1
    - spec: cray-mpich@8.1.23%cce
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0
    - spec: cray-mpich@8.1.23%aocc
      modules:
      - cray-mpich/8.1.23
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/aocc/3.0
    buildable: false
  cray-libsci:
    externals:
    - spec: cray-libsci@22.12.1.1%gcc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/gnu/9.1/x86_64
    - spec: cray-libsci@21.08.1.2%cce
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/cray/9.0/x86_64
    - spec: cray-libsci@22.08.1.1%aocc
      modules:
      - cray-libsci/22.12.1.1
      prefix: /opt/cray/pe/libsci/22.12.1.1/aocc/2.0/x86_64
    buildable: false
  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.10.3 target=zen2
      modules:
      - craype-x86-rome
      - cray-fftw/3.3.10.3
      prefix: /opt/cray/pe/fftw/3.3.10.3/x86_rome
    buildable: false
  # more cray
  xpmem:
    externals:
    - spec: xpmem@2.4.4
      modules:
      - xpmem/xpmem/2.5.2-2.4_3.30__gd0f7936.shasta
      prefix: /opt/cray/xpmem/xpmem/2.5.2-2.4_3.30__gd0f7936.shasta
    buildable: false
  libfabric:
    externals:
    - spec: libfabric@1.12.1.2.2.0.0
      modules:
      - libfabric/1.12.1.2.2.0.0
      prefix: /opt/cray/libfabric/1.11.0.4.128
    buildable: false
  #ucx:
  #  externals:
  #  - spec: ucx@2.7.0-1
  #    modules:
  #    - cray-ucx/2.7.0-1
  #    prefix: /opt/cray/pe/cray-ucx/2.7.0-1/ucx
  #  buildable: false
  papi:
    externals:
    - spec: papi@6.0.0.17
      modules:
      - papi/6.0.0.17
      prefix: /opt/cray/pe/papi/6.0.0.17
    buildable: false

# cray hdf5
# cray parallel-netcdf
# cray netcdf
# taken out, as cray is dropping support, and there are missing APIs any way

# python additions, based on loading cray-python and running pip list 
# we have tried to use them as externals, but Spack does not use them correctly:
# 1. if specified with ^python@3.9.7, concretisation always fail
# 2. if specified without ^python@3.9.7, would be used also with the wrong python versions
# therefore, taken out

