compilers::
- compiler:
    spec: gcc@8.4.1
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: any
    modules: []
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
      paths:
      cc: /mnt/lustre/tursafs1/apps/gcc/9.3.0/bin/gcc
      cxx: /mnt/lustre/tursafs1/apps/gcc/9.3.0/bin/g++
      f77: /mnt/lustre/tursafs1/apps/gcc/9.3.0/bin/gfortran
      fc: /mnt/lustre/tursafs1/apps/gcc/9.3.0/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
